"use client";

import { Day } from "../../../types";

// Dynamically generate and download the PDF
export async function downloadItineraryPDF(itinerary: Day[], archetype: string | null) {
  // Dynamic import to avoid SSR issues
  const { Document, Page, Text, View, StyleSheet, pdf } = await import("@react-pdf/renderer");
  const { createElement } = await import("react");

  const styles = StyleSheet.create({
    page: { padding: 40, fontFamily: "Helvetica", backgroundColor: "#fff" },
    title: { fontSize: 24, fontWeight: "bold", marginBottom: 4, color: "#065f46" },
    subtitle: { fontSize: 10, color: "#71717a", marginBottom: 24 },
    dayCard: { marginBottom: 16, borderWidth: 1, borderColor: "#e4e4e7", borderRadius: 6, padding: 12 },
    dayHeader: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    dayNumber: { fontSize: 14, fontWeight: "bold", color: "#065f46", marginRight: 8 },
    dayCity: { fontSize: 14, fontWeight: "bold", color: "#18181b" },
    dayProvince: { fontSize: 9, color: "#a1a1aa", marginLeft: 6 },
    travel: { fontSize: 8, color: "#71717a", marginBottom: 6, fontStyle: "italic" },
    airport: { fontSize: 8, color: "#3b82f6", marginBottom: 6 },
    stop: { fontSize: 10, color: "#27272a", marginBottom: 1, paddingLeft: 10 },
    stopDesc: { fontSize: 8, color: "#71717a", marginBottom: 4, paddingLeft: 10 },
    stopType: { fontSize: 8, color: "#a1a1aa" },
    hotel: { fontSize: 10, color: "#92400e", marginTop: 8, paddingTop: 6, borderTopWidth: 1, borderTopColor: "#f4f4f5" },
    hotelLabel: { fontSize: 7, color: "#a1a1aa", textTransform: "uppercase", letterSpacing: 1, marginBottom: 2 },
    footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 7, color: "#d4d4d8", textAlign: "center" },
  });

  const travelLabel = (method: string) => {
    switch (method) {
      case "flight": return "✈ Flight";
      case "drive": return "🚗 Drive";
      case "train": return "🚆 Train";
      case "boat": return "⛴ Boat";
      default: return "";
    }
  };

  const stopIcon = (type: string) => {
    switch (type) {
      case "park": return "🌲";
      case "restaurant": return "🍽";
      case "attraction": return "📸";
      case "hotel": return "🏨";
      case "airport": return "✈";
      default: return "📍";
    }
  };

  // Build the document using createElement (can't use JSX in dynamic import context easily)
  const h = createElement;

  const doc = h(Document, null,
    h(Page, { size: "A4", style: styles.page },
      h(Text, { style: styles.title }, "BeaverTrails Itinerary"),
      h(Text, { style: styles.subtitle }, archetype ? `Crafted for: ${archetype}` : "Your personalized Canadian adventure"),

      ...itinerary.map((day) =>
        h(View, { key: day.date_offset, style: styles.dayCard, wrap: false },
          // Day header
          h(View, { style: styles.dayHeader },
            h(Text, { style: styles.dayNumber }, `Day ${day.date_offset}`),
            h(Text, { style: styles.dayCity }, day.city),
            h(Text, { style: styles.dayProvince }, day.province),
          ),

          // Travel info
          day.travel_time_from_prev_hours > 0
            ? h(Text, { style: styles.travel }, `${travelLabel(day.travel_method_from_prev)} — ${day.travel_time_from_prev_hours}h from previous city`)
            : null,

          // Airport
          day.airport?.name
            ? h(Text, { style: styles.airport }, `✈ ${day.airport.name}`)
            : null,

          // Stops
          ...(day.stops || []).flatMap((stop, i) => [
            h(Text, { key: `s${i}`, style: styles.stop }, `${stopIcon(stop.type)}  ${stop.name}`),
            stop.description ? h(Text, { key: `d${i}`, style: styles.stopDesc }, stop.description) : null,
          ]),

          // Hotel
          day.overnight_hotel
            ? h(View, { style: styles.hotel },
                h(Text, { style: styles.hotelLabel }, "STAY AT"),
                h(Text, null, `🛏  ${day.overnight_hotel}`),
              )
            : null,
        )
      ),

      h(Text, { style: styles.footer }, "Generated by BeaverTrails — beavertrails.app"),
    )
  );

  // Generate blob and download
  const blob = await pdf(doc).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "beavertrails-itinerary.pdf";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
